### ISSUE TITLE
purpose of goroutines used in RunCommand

### ISSUE THREAD

**Issue by sigmonsays** [bcicen/go-haproxy#6]
https://github.com/sigmonsays/go-haproxy/blob/master/client.go#L24

I dont understand why the write and read is done in separate goroutines here. What is the point?

**Comment by bcicen** [comment]
Good point; the separate routines aren't necessary in the client currently. Removed in https://github.com/bcicen/go-haproxy/commit/46e7edb10f5adcc0f922d836fab0d48677c1f2ff
